### ISSUE TITLE
Maybe in Tomcat?

### ISSUE THREAD

**Issue by cyberphone** [schnatterer/tomcat-reloading-connector#3]
Pardon for using GitHub, I didn't find any other means :)
https://bz.apache.org/bugzilla/show_bug.cgi?id=65770

Anyway, I'm using your library together with Letsencrypt's certbot.  I'm still waiting for the first renewal...

Regards,
Anders

**Comment by schnatterer** [comment]
Nice idea, thanks for letting me know!

I actually never considered pushing my implementaion upstream. I'm convinced there are better ways of implemeting it for someone who is more experienced with tomcat internals.
Still makes a lot of sense to include a feature like this into tomcat core IMO. Newer servers from non-java technological ecosystem often include ACME/LE by default. With Tomcat we're stuck with an anti-intuitive technology from the 90s like JMX to implement cert reloading manually 🤔

Keeping my fingers crossed for your initiative on the Apache BZ 👍

Interesting to read that you use this in conjunction with certbot. My showcase example uses a bash-only cert reloader (dehydrated) https://github.com/schnatterer/letsencrypt-tomcat
Did you automate your setup and would you mind sharing it? Maybe as a gist? I'd gladly add a link to the README as another example.

**Comment by cyberphone** [comment]
Hi @schnatterer, you have done a lot more than I!
I only installed https://certbot.eff.org/, put your reloading-connector in Tomcat's lib folder, and updated the Tomcat SSL configuration in server.xml to point to the file created by certbot.  I have a whole bunch of different host names which made certbot a good choice:

```xml
  <Service name="Catalina">

    <Connector port="80" protocol="org.apache.coyote.http11.Http11AprProtocol"
               connectionTimeout="20000"
               redirectPort="443" />

    <Connector port="443" protocol="info.schnatterer.tomcat.ReloadingHttp11AprProtocol"
               maxThreads="150" SSLEnabled="true" defaultSSLHostConfigName="webpki.org">
        <SSLHostConfig hostName="webpki.org">
            <Certificate certificateKeyFile="/etc/letsencrypt/live/webpki.org/privkey.pem"
                         certificateFile="/etc/letsencrypt/live/webpki.org/cert.pem"
                         certificateChainFile="/etc/letsencrypt/live/webpki.org/chain.pem"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>

    <Engine name="Catalina" defaultHost="webpki.org">

      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="webpki.org" appBase="webapps"
            unpackWARs="true" autoDeploy="true">
      </Host>
      <Host name="spaceshop.webpki.org" appBase="spaceshop.webpki"
            unpackWARs="true" autoDeploy="true">
      </Host>
      <Host name="test.webpki.org" appBase="test.webpki"
            unpackWARs="true" autoDeploy="true">
      </Host>
      <Host name="mybank.webpki.org" appBase="mybank.webpki"
            unpackWARs="true" autoDeploy="true">
      </Host>
 
      <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
             prefix="localhost_access_log" suffix=".txt"
             pattern="%h %l %u %t &quot;%r&quot; %s %b"/>
    </Engine>
  </Service>
```

This was done very recently so I have yet to see it renew.  I have though verified that reloading works  👍

**Comment by schnatterer** [comment]
Cool, thanks for sharing, @cyberphone !
